Added sparse matrixes to save space.
cazevedo/gspn-framework pull request #5
Opened 2019-09-12 09:54 UTC by PedroACaldeira

**add_places**
-Criei o mapping e blindei para o caso de adicionarmos places a meio da execução;
-Faço place_mapping[name] = i, onde i é um inteiro cujo valor inicial depende se existiam places(i=len(places)) ou não (i=0);
-Adicionei self.__place_mapping à classe.

**add_transition**
-Fiz essencialmente a mesma coisa que fiz no de cima

**add_arcs**
-tenho dois for encadeados que percorrem cada transição e vou adicionando os valores do mapping ao vetor self.__arc_in/out_m

2019-09-24 21:38 UTC, PedroACaldeira commented
Melhorei o que foi preciso melhorar em gspn.py
Dei fix ao desenho das edges.

2019-10-01 14:45 UTC, cazevedo requested changes

2019-10-01 14:45 UTC, cazevedo commented on gspn_tools.py
> +        print(sparse_in_coords)
delete print

2019-10-01 14:45 UTC, cazevedo commented on gspn.py
>          print('arc_out:', arc_out)
delete print

2019-10-01 14:45 UTC, cazevedo commented on gspn.py
>          print('arc_out_m:', self.__arc_out_m)
delete print

2019-10-01 14:45 UTC, cazevedo commented on gspn.py
>  import pandas as pd
delete import

2019-10-01 14:47 UTC, cazevedo commented
Changes sum-up:
-Memory and performance optimization of arcs, through the use of sparse matrices.
-Refactored add_transition, add_places, add_arcs and draw_gspn methods to address sparse matrices manipulation.

2019-10-01 17:24 UTC, cazevedo commented on gspn.py
> +        exemplo: {'p1':  ['t1','t2], 'p2': ['t3']}
change to example

2019-10-01 17:24 UTC, cazevedo commented on gspn.py
>          :return: (pandas DataFrame, pandas DataFrame)
fix documentation, no longer DataFrame

2019-10-01 17:25 UTC, cazevedo commented on gspn.py
>          :return: (dict, dict) Dictionaries of input and output arcs connected to the input element
fix documentation, no longer DataFrame

2019-10-01 17:27 UTC, cazevedo commented on gspn.py
>          """
add documentation (similar to add_transitions)

2019-10-01 17:46 UTC, PedroACaldeira commented
Removed debug prints;
Changed language of some lines of code from PT to ENG;
Added documentation on add_places.

2019-10-01 17:50 UTC, cazevedo commented on gspn.py
> +        :param set_initial_marking: (list int) denotes the initial marking of the petri net
this is a bool, not a list, if True, the list ntokens will be set as the initial marking, and will not be set otherwise.

2019-10-01 17:52 UTC, cazevedo commented on gspn.py
> +        :param ntokens: (list int) denotes the maximum number of tokens of each place
not the maximum number of tokens, but the current number of tokens of the given places. can be set as the initial marking depending whether the set_initial_marking parameter is True or False.

2019-10-01 18:18 UTC, PedroACaldeira commented
Minor documentation errors fixed.

2019-10-02 10:28 UTC, cazevedo commented
Good job @PedroACaldeira

2019-10-02 10:29 UTC, merged